# Cloud Native Buildpacks configuration
# This file configures the build process for Easypanel/Heroku deployment

[build]
# Explicitly use the Heroku builder version 24 (Ubuntu 24.04 based)
builder = "heroku/builder:24"

[[build.buildpacks]]
# Node.js buildpack for the application
id = "heroku/nodejs"